# shellcheck shell=sh
#
# One interface over launchd (macOS) and a systemd user unit (Linux) — #621.
#
# Before this, `install.sh` (generated by release.sh) and `uninstall.sh` each carried
# their own `[ "$OS" = "Darwin" ]` branch, and `restart.sh` carried none at all: it
# called `launchctl unload/load` unconditionally, so on Linux both the developer's
# deploy loop and the in-app auto-update (which spawns `restart.sh --refresh`) were
# simply broken. The plist and the unit are now written in exactly one place, and the
# three consumers all drive the daemon through the same verbs.
#
# ============================ THIS IS A LIBRARY ==============================
#
# It is sourced, never executed: no shebang-as-entrypoint, no `main`, no
# `case "$1"`, no trailing invocation, and the file is mode 644 with no exec bit.
# That is load-bearing, not stylistic.
#
# CLAUDE.md's rule is that a deepsteve restart can never happen unilaterally, because
# the only way to trigger one is `./restart.sh`, which stays behind Claude Code's
# permission prompt and must never be allowlisted. If this file grew an exec bit and
# an argument dispatcher, `./service.sh restart` would be a second, unguarded path to
# the same thing. With neither, that is unrepresentable rather than merely discouraged
# — and test/unit/service-lib.test.js asserts both properties so it stays that way.
#
# `./status.sh` is the read-only companion, and is safe to allowlist.
#
# ================================ CONVENTIONS ================================
#
#   accessors   (ds_platform, ds_port, …)      print one line, always exit 0
#   predicates  (ds_is_running, …)             print nothing; EXIT 0 MEANS TRUE
#   mutators    (ds_service_start, …)          diagnostics to stderr; 0 = success
#
# POSIX sh only — no `[[`, no arrays, no `local -n`. `local` itself is not POSIX but
# is universal in dash/bash/zsh/ksh and the CI unit job sources this with dash.
#
# NOTE ON `set -e`: install.sh runs under it; restart.sh and uninstall.sh do not.
# Nothing here may enable it (a sourced `set -e` would silently change the caller's
# shell options), and ds_service_stop deliberately always returns 0 — see there.

DS_DEFAULT_PORT=3000
DS_LAUNCHD_LABEL=com.deepsteve
DS_SYSTEMD_UNIT=deepsteve

# ---------------------------------------------------------------- accessors

# `darwin` or `linux`. Everything that is not macOS is treated as the systemd arm,
# matching the "Darwin or else" shape release.sh and logging.js already use.
#
# DEEPSTEVE_PLATFORM is a test/diagnostic override, and it is what makes this library
# testable at all: one Linux CI runner can exercise BOTH arms. Without it half of this
# file could never be asserted anywhere.
ds_platform() {
    if [ -n "${DEEPSTEVE_PLATFORM:-}" ]; then
        printf '%s\n' "$DEEPSTEVE_PLATFORM"
        return 0
    fi
    case "$(uname -s 2>/dev/null)" in
        Darwin) printf 'darwin\n' ;;
        *)      printf 'linux\n' ;;
    esac
}

# The install + state dir. Twin of paths.js's stateDir(); DEEPSTEVE_HOME is honored on
# both sides, and is a daemon-side override for tests and second instances rather than
# a supported way to relocate an install (paths.js says why).
ds_install_dir() {
    printf '%s\n' "${DEEPSTEVE_HOME:-$HOME/.deepsteve}"
}

# Twin of paths.js's logDir(). These two MUST agree: the service definition written
# here is what actually opens the daemon's stdout/stderr, and logging.js rotates them
# through the fds it was handed. test/unit/service-definition.test.js compares the two
# implementations directly, which is what finally enforces the "must mirror release.sh"
# comment logging.js has carried since #557.
ds_log_dir() {
    if [ -n "${DEEPSTEVE_LOG_DIR:-}" ]; then
        printf '%s\n' "$DEEPSTEVE_LOG_DIR"
    elif [ "$(ds_platform)" = "darwin" ]; then
        printf '%s\n' "$HOME/Library/Logs"
    else
        printf '%s\n' "$HOME/.local/share/deepsteve/logs"
    fi
}

ds_service_path() {
    if [ "$(ds_platform)" = "darwin" ]; then
        printf '%s\n' "$HOME/Library/LaunchAgents/$DS_LAUNCHD_LABEL.plist"
    else
        printf '%s\n' "$HOME/.config/systemd/user/$DS_SYSTEMD_UNIT.service"
    fi
}

# The node the daemon should run under.
#
# Prefers the path ALREADY RECORDED in the service definition, while it is still
# executable, and only falls back to `command -v node`. That ordering matters more
# than it looks: on a machine using nvm the recorded path is something like
# ~/.nvm/versions/node/v22.14.0/bin/node, and without this a ./restart.sh run from a
# developer's shell would silently re-point the daemon at whatever node happened to be
# active — a version they may later `nvm uninstall`, bricking the daemon with no
# diagnosable message. On a fresh install there is no file yet, so this degrades to
# `command -v node`, which is exactly what install.sh always did.
ds_node_path() {
    local sp recorded
    sp="$(ds_service_path)"
    recorded=""
    if [ -f "$sp" ]; then
        if [ "$(ds_platform)" = "darwin" ]; then
            recorded=$(awk '/<key>ProgramArguments<\/key>/{f=1;next}
                            f&&/<string>/{gsub(/.*<string>|<\/string>.*/,"");
                                          gsub(/^[ \t]+|[ \t]+$/,""); print; exit}' "$sp" 2>/dev/null)
        else
            recorded=$(sed -n 's/^ExecStart="\{0,1\}\([^" ]*\)"\{0,1\}.*/\1/p' "$sp" 2>/dev/null | head -1)
        fi
    fi
    if [ -n "$recorded" ] && [ -x "$recorded" ]; then
        printf '%s\n' "$recorded"
        return 0
    fi
    command -v node 2>/dev/null
}

# The port the daemon will actually bind.
#
# Read from the installed service definition, which is the real source of truth — the
# daemon takes PORT from its environment and the definition is what sets it.
# Deliberately NOT $PORT: a developer with PORT exported in their shell would otherwise
# silently mis-target every control curl in restart.sh.
ds_port() {
    local sp p
    if [ -n "${DEEPSTEVE_PORT:-}" ]; then
        printf '%s\n' "$DEEPSTEVE_PORT"
        return 0
    fi
    sp="$(ds_service_path)"
    p=""
    if [ -f "$sp" ]; then
        if [ "$(ds_platform)" = "darwin" ]; then
            p=$(awk '/<key>PORT<\/key>/{getline; gsub(/.*<string>|<\/string>.*/,"");
                                        gsub(/^[ \t]+|[ \t]+$/,""); print; exit}' "$sp" 2>/dev/null)
        else
            p=$(sed -n 's/^Environment="\{0,1\}PORT=\([0-9][0-9]*\).*/\1/p' "$sp" 2>/dev/null | head -1)
        fi
    fi
    case "$p" in
        ''|*[!0-9]*) p="$DS_DEFAULT_PORT" ;;
    esac
    printf '%s\n' "$p"
}

# Control-plane URL. Plain `localhost`, never deepsteve.localhost: this is non-browser,
# bearer-authed traffic and must not depend on *.localhost resolving (CLAUDE.md #545).
ds_url() {
    printf 'http://localhost:%s\n' "$(ds_port)"
}

# --------------------------------------------------------------- predicates

# Is a usable service manager present? On Linux `systemctl --user show-environment`
# probes the user bus specifically — a better question than `systemctl --user status`,
# which returns nonzero merely because some unrelated unit is failed.
ds_manager_available() {
    if [ "$(ds_platform)" = "darwin" ]; then
        command -v launchctl >/dev/null 2>&1
    else
        command -v systemctl >/dev/null 2>&1 && systemctl --user show-environment >/dev/null 2>&1
    fi
}

ds_is_running() {
    if [ "$(ds_platform)" = "darwin" ]; then
        launchctl list 2>/dev/null | grep -q "[[:space:]]$DS_LAUNCHD_LABEL\$"
    else
        systemctl --user is-active --quiet "$DS_SYSTEMD_UNIT" 2>/dev/null
    fi
}

ds_is_enabled() {
    if [ "$(ds_platform)" = "darwin" ]; then
        # launchd has no separate enabled state for us: RunAtLoad + a loaded job is it.
        [ -f "$(ds_service_path)" ]
    else
        systemctl --user is-enabled --quiet "$DS_SYSTEMD_UNIT" 2>/dev/null
    fi
}

# Is anything listening on the daemon's port?
#
# This replaced `lsof -i :3000 -sTCP:LISTEN` (#621). lsof is absent on minimal Linux
# images, ss needs iproute2 and fuser needs psmisc — three tools, three flag dialects,
# none guaranteed. node is a hard dependency that install.sh downloads if missing, so
# a connect probe is the one check available everywhere the daemon can run.
#
# Fails OPEN (reports "free") when node cannot be found, which is the same behavior
# the old lsof call had when lsof was missing: a restart is never blocked by the
# absence of a probing tool.
#
# Two honest narrowings vs lsof, both strictly better than the tool not existing: this
# cannot see a listener bound ONLY to a non-loopback address (it covers 0.0.0.0 and
# 127.0.0.1), and it probes IPv4 only — the default bind is 127.0.0.1, so that is
# theoretical.
ds_port_in_use() {
    local node port
    port="${1:-$(ds_port)}"
    node="$(ds_node_path)"
    [ -n "$node" ] || return 1
    "$node" -e '
const net = require("net");
const s = net.connect({ host: "127.0.0.1", port: Number(process.argv[1]) });
s.setTimeout(1500);
s.on("connect", () => { s.destroy(); process.exit(0); });
s.on("timeout", () => { s.destroy(); process.exit(1); });
s.on("error", () => process.exit(1));
' "$port" >/dev/null 2>&1
}

ds_is_responding() {
    local secs
    secs="${1:-2}"
    command -v curl >/dev/null 2>&1 || return 1
    curl -sf -m "$secs" "$(ds_url)/healthz" >/dev/null 2>&1
}

# Does this user's systemd instance survive logout? Always true on macOS, where launchd
# runs a per-user domain regardless.
ds_linger_enabled() {
    [ "$(ds_platform)" = "darwin" ] && return 0
    [ -e "/var/lib/systemd/linger/$(id -un)" ] && return 0
    loginctl show-user "$(id -un)" --property=Linger 2>/dev/null | grep -q 'Linger=yes'
}

# ----------------------------------------------------------------- mutators

# Write the plist / unit.
#
# The heredoc delimiters below are DELIBERATELY UNQUOTED: $ds_node, $ds_install,
# $ds_log, $HOME and $node_bin are expanded HERE, at write time, so the file on disk
# holds literal absolute paths. That is unchanged from the inline block release.sh used
# to emit — a heredoc expands when it EXECUTES, and a function body in a sourced file
# is no different. Consequence to respect when editing: neither body may contain a bare
# `$`, a backtick, or a backslash that is not an intended expansion.
ds_service_write() {
    local sp ds_install ds_log ds_port_val ds_node node_bin
    # Named ds_node, not NODE_PATH: that is a real Node environment variable (module
    # resolution), and install.sh has a global by that name.
    ds_node="$(ds_node_path)"
    sp="$(ds_service_path)"
    ds_install="$(ds_install_dir)"
    ds_log="$(ds_log_dir)"
    ds_port_val="$DS_DEFAULT_PORT"

    if [ -z "$ds_node" ]; then
        echo "deepsteve: no node found — refusing to write $sp" >&2
        return 1
    fi
    node_bin="$(dirname "$ds_node")"
    mkdir -p "$(dirname "$sp")" "$ds_log" || return 1

    if [ "$(ds_platform)" = "darwin" ]; then
        cat > "$sp" << PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$DS_LAUNCHD_LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>$ds_node</string>
        <string>$ds_install/server.js</string>
    </array>
    <key>WorkingDirectory</key>
    <string>$ds_install</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>NODE_ENV</key>
        <string>production</string>
        <key>PORT</key>
        <string>$ds_port_val</string>
        <key>DEEPSTEVE_BIND</key>
        <string>127.0.0.1</string>
        <key>PATH</key>
        <string>$ds_install/node/bin:$HOME/.local/bin:$node_bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>$ds_log/deepsteve.log</string>
    <key>StandardErrorPath</key>
    <string>$ds_log/deepsteve.error.log</string>
</dict>
</plist>
PLISTEOF
    else
        cat > "$sp" << UNITEOF
[Unit]
Description=deepsteve daemon
After=network.target

[Service]
Type=simple
ExecStart=$ds_node $ds_install/server.js
WorkingDirectory=$ds_install
Environment=NODE_ENV=production
Environment=PORT=$ds_port_val
Environment=DEEPSTEVE_BIND=127.0.0.1
Environment=PATH=$ds_install/node/bin:$HOME/.local/bin:$node_bin:/usr/local/bin:/usr/bin:/bin
Restart=always
RestartSec=5
StandardOutput=append:$ds_log/deepsteve.log
StandardError=append:$ds_log/deepsteve.error.log

[Install]
WantedBy=default.target
UNITEOF
    fi
}

ds_daemon_reload() {
    [ "$(ds_platform)" = "darwin" ] && return 0
    systemctl --user daemon-reload 2>/dev/null || true
}

# Stop the daemon. IDEMPOTENT, AND ALWAYS RETURNS 0 — deliberately.
#
# install.sh runs under `set -e`. Its old inline `launchctl unload "$SERVICE_PATH"`
# survived that only because launchctl is famously lax about exit codes;
# `systemctl --user stop` on a unit that does not exist yet is not, and would have
# aborted every fresh Linux install at the last step. "Already stopped" is success.
ds_service_stop() {
    if [ "$(ds_platform)" = "darwin" ]; then
        launchctl unload "$(ds_service_path)" 2>/dev/null || true
    else
        systemctl --user stop "$DS_SYSTEMD_UNIT" 2>/dev/null || true
    fi
    return 0
}

# Start the daemon. Unlike stop, this does NOT swallow failure — callers wrap it with
# a message so `set -e` can never abort silently.
ds_service_start() {
    if [ "$(ds_platform)" = "darwin" ]; then
        launchctl load "$(ds_service_path)"
    else
        # reset-failed first: once a crash loop trips StartLimitBurst the unit latches
        # `failed` and every subsequent `start` fails until it is cleared, which reads
        # as "restart.sh silently did nothing".
        systemctl --user reset-failed "$DS_SYSTEMD_UNIT" 2>/dev/null || true
        systemctl --user daemon-reload 2>/dev/null || true
        systemctl --user enable --now "$DS_SYSTEMD_UNIT"
    fi
}

# The command a human should run if start failed, so a wedged daemon is one paste away.
ds_start_hint() {
    if [ "$(ds_platform)" = "darwin" ]; then
        printf 'launchctl load %s\n' "$(ds_service_path)"
    else
        printf 'systemctl --user enable --now %s   # then: journalctl --user -u %s -n 50\n' \
            "$DS_SYSTEMD_UNIT" "$DS_SYSTEMD_UNIT"
    fi
}

ds_service_uninstall() {
    ds_service_stop
    if [ "$(ds_platform)" != "darwin" ]; then
        systemctl --user disable "$DS_SYSTEMD_UNIT" 2>/dev/null || true
    fi
    rm -f "$(ds_service_path)"
    ds_daemon_reload
    return 0
}

# Wait for the daemon to be fully gone: first the service manager reports it stopped,
# then the port is actually free (a child can hold the socket briefly after the parent
# exits). 0 = stopped, 1 = timed out.
ds_wait_stopped() {
    local limit waited
    limit="${1:-15}"
    waited=0
    while [ "$waited" -lt "$limit" ] && ds_is_running; do
        sleep 1
        waited=$((waited + 1))
    done
    waited=0
    while [ "$waited" -lt 5 ] && ds_port_in_use; do
        sleep 1
        waited=$((waited + 1))
    done
    ds_is_running && return 1
    return 0
}

ds_wait_responding() {
    local limit waited
    limit="${1:-15}"
    waited=0
    while [ "$waited" -lt "$limit" ]; do
        ds_is_responding 1 && return 0
        sleep 1
        waited=$((waited + 1))
    done
    return 1
}

# Without lingering, `systemd --user` is torn down when the user's last login session
# ends: ssh in, install, log out, daemon dies — and it never starts at boot. On the
# headless box this whole issue exists for, that is the difference between a deployment
# and a demo.
#
# Deliberately NOT run automatically. `loginctl enable-linger` writes outside $HOME and
# its polkit action is typically auth_admin_keep for a REMOTE session, so a curl|bash
# installer would either hang on a password prompt or emit a scary permission error at
# the worst possible moment. Automation opts in with DEEPSTEVE_ENABLE_LINGER=1; humans
# get one visible line, repeated by ./status.sh forever rather than lost in scrollback.
ds_linger_note() {
    [ "$(ds_platform)" = "darwin" ] && return 0
    ds_linger_enabled && return 0
    echo ""
    echo "Note: user lingering is off, so deepsteve stops when your last login session"
    echo "      ends and does not start at boot. On a headless box, enable it with:"
    echo ""
    echo "          loginctl enable-linger $(id -un)"
    echo ""
}

ds_maybe_enable_linger() {
    [ "$(ds_platform)" = "darwin" ] && return 0
    ds_linger_enabled && return 0
    if [ "${DEEPSTEVE_ENABLE_LINGER:-}" = "1" ]; then
        loginctl enable-linger "$(id -un)" 2>/dev/null && return 0
    fi
    ds_linger_note
    return 0
}

# Human-readable status. Multi-line, printed to stdout. Callers decide the exit code.
ds_service_status() {
    local sp node port
    sp="$(ds_service_path)"
    node="$(ds_node_path)"
    port="$(ds_port)"

    printf 'deepsteve\n'
    if [ "$(ds_platform)" = "darwin" ]; then
        printf '  platform      macOS (launchd)\n'
    else
        printf '  platform      linux (systemd --user)\n'
    fi

    if [ -f "$sp" ]; then
        printf '  service       %s  present\n' "$sp"
    else
        printf '  service       %s  MISSING — run install.sh\n' "$sp"
    fi

    if ds_is_running; then
        if ds_is_enabled; then
            printf '  state         running (enabled)\n'
        else
            printf '  state         running (not enabled at boot)\n'
        fi
    else
        printf '  state         not running\n'
    fi

    if [ "$(ds_platform)" != "darwin" ]; then
        if ds_linger_enabled; then
            printf '  lingering     on\n'
        else
            printf '  lingering     OFF — stops when your last login session ends, and does\n'
            printf '                not start at boot.  Fix:  loginctl enable-linger %s\n' "$(id -un)"
        fi
    fi

    if ds_port_in_use "$port"; then
        printf '  port          %s  listening\n' "$port"
    else
        printf '  port          %s  nothing listening\n' "$port"
    fi

    if ds_is_responding 2; then
        printf '  health        ok    %s/healthz\n' "$(ds_url)"
    else
        printf '  health        FAIL  %s/healthz\n' "$(ds_url)"
    fi

    if [ -n "$node" ]; then
        printf '  node          %s\n' "$node"
    else
        printf '  node          NOT FOUND — the daemon cannot start\n'
    fi

    printf '  logs          %s\n' "$(ds_log_dir)"
    # The daemon binds loopback only, on purpose (#536). Say how to reach it from
    # elsewhere, since "runnable on a box that isn't the laptop" is the point of #621.
    printf '  remote access loopback-only bind — ssh -L %s:localhost:%s <host>\n' "$port" "$port"
}
